site_name: Blacksun Theme for MkDocs
repo_name: jastuccio/blacksun-mkdocs-theme
repo_url: https://github.com/jastuccio/blacksun-mkdocs-theme
site_url: https://jastuccio.github.io/blacksun-mkdocs-theme/
copyright: Copyright &copy; jastuccio

nav:
    - Home: index.md
    - Getting Started: nav/getting-started.md
    - Settings:
      - nav/settings/custom-highlight.md
    - Development:
      - nav/development/development-guide.md
      - nav/development/release-notes.md

theme:
  name: blacksun
  logo: assets/img/blacksun.png
  favicon: assets/img/favicon.ico
  # You can add theme-specific features here later
